/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme;

/** 
 *
 * @author jabes
 */
public class Inicio extends javax.swing.JFrame {

    public static login frmLog;
    
    public Inicio() {
        initComponents();
        iniciarTemporizador(); // Llamar al método para iniciar el temporizador
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel1.setText("Bienvenido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarTemporizador() {
        Timer timer = new Timer(1500, new ActionListener() { // 5 segundos
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frmLog == null) {
                    frmLog = new login();
                }
                frmLog.setVisible(true); // Mostrar el formulario login
                dispose(); // Cerrar la ventana actual
            }
        });
        timer.setRepeats(false); // Ejecutar solo una vez
        timer.start(); // Iniciar el temporizador
    }
    /**
     * @param args the command line arguments
     */
     public static void main(String[] args) {
        try {
            FlatDarkFlatIJTheme.setup(); // Aplica el tema Cupertino Dark
        } catch (Exception ex) {
            System.err.println("No se pudo aplicar el tema: " + ex.getMessage());
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Inicio().setVisible(true); // Inicia tu ventana principal
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
